# Generated by Django 5.2.6 on 2025-10-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_no', models.IntegerField()),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('query', models.CharField(max_length=50)),
                ('source_url', models.CharField(max_length=200)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramas.drama')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramas.drama')),
            ],
            options={
                'unique_together': {('source_name', 'external_id')},
            },
        ),
    ]
