# Generated by Django 5.2.6 on 2025-10-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='episode_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episodeinfo',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='dramas.drama'),
        ),
    ]
