# Generated by Django 5.2.6 on 2025-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0002_drama_episode_count_alter_episodeinfo_drama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='episode_count',
        ),
        migrations.AddField(
            model_name='drama',
            name='img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
