# Generated by Django 5.2.6 on 2025-10-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0003_remove_drama_episode_count_drama_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='genre',
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='dramas.drama')),
            ],
        ),
    ]
