# Generated by Django 5.2.6 on 2025-10-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0004_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeinfo',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
