# Generated by Django 5.2.6 on 2025-09-30 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_drama_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.drama')),
            ],
            options={
                'unique_together': {('source_name', 'external_id')},
            },
        ),
    ]
