# Generated by Django 5.2.6 on 2025-10-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_drama_is_airing_alter_drama_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_no', models.IntegerField()),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('query', models.CharField(max_length=50)),
                ('source_url', models.CharField(max_length=200)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.drama')),
            ],
        ),
    ]
