# Generated by Django 5.2.6 on 2025-09-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_externalidmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='is_airing',
        ),
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
