name: CI
on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.10

      - name: Setup virtual environment
        run: uv sync
     
      - name: Run Django test
        working-directory: src
        run: |
          uv run python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: "backend.settings"
