name: Lint
on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # uv 설치
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.10

      - name: Setup virtual environment
        run: |
          uv sync
          uv pip install flake8 black isort

      - name: Run linters
        working-directory: src
        run: |
          uv run flake8 . --max-line-length=9999
          uv run black --check .
          uv run isort --check-only .
